application:
  port: 9000

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "1password2"
  database_name: "blog"
logger:
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or json
  format: pretty
